const tanks = [
  {
    id: 1,
    weight: '2.7kg',
    brand: 'Regasco',
    image: '/regasco2.7.png',
    price: '₱320',
  },
  {
    id: 2,
    weight: '11kg',
    brand: 'Regasco',
    image: '/regasco11.png',
    price: '₱1050',
  },
  {
    id: 3,
    weight: '22kg',
    brand: 'Regasco',
    image: '/regasco22.png',
    price: '₱2100',
  },
  {
    id: 4,
    weight: '50kg',
    brand: 'Regasco',
    image: '/regasco50.png',
    price: '₱4300',
  },
  {
    id: 5,
    weight: '2.7kg',
    brand: 'Pryce',
    image: '/pryce2.7.png',
    price: '₱320',
  },
  {
    id: 6,
    weight: '11kg',
    brand: 'Pryce',
    image: '/pryce11.png',
    price: '₱980',
  },
  {
    id: 7,
    weight: '22kg',
    brand: 'Pryce',
    image: '/pryce22.png',
    price: '₱2000',
  },
  {
    id: 8,
    weight: '50kg',
    brand: 'Pryce',
    image: '/pryce50.png',
    price: '₱4300',
  },
  {
    id: 9,
    weight: '2.7kg',
    brand: 'Equigaz',
    image: '/equigaz2.7.png',
    price: '₱250',
  },
  {
    id: 10,
    weight: '11kg',
    brand: 'Equigaz',
    image: '/equigaz11.png',
    price: '₱930',
  },
  {
    id: 11,
    weight: '22kg',
    brand: 'Equigaz',
    image: '/equigaz22.png',
    price: '₱1800',
  },
  {
    id: 12,
    weight: '50kg',
    brand: 'Equigaz',
    image: '/equigaz50.png',
    price: '₱4000',
  },
  {
    id: 13,
    weight: '2.7kg',
    brand: 'Shine Gas',
    image: '/shinegas2.7.png',
    price: '₱250',
  },
  {
    id: 14,
    weight: '11kg',
    brand: 'Shine Gas',
    image: '/shinegas11.png',
    price: '₱930',
  },
  {
    id: 15,
    weight: '22kg',
    brand: 'Shine Gas',
    image: '/shinegas22.png',
    price: '₱1800',
  },
  {
    id: 16,
    weight: '50kg',
    brand: 'Shine Gas',
    image: '/shinegas50.png',
    price: '₱4000',
  },
];

export default tanks;